services:
  database:
    image: database:1.0.0
    container_name: postgres-c-mup
    env_file:
      - .env
    user: postgres
    environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DATABASE}
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - 6779:${POSTGRES_PORT}
    volumes:
      - database-v-mup:/var/lib/postgresql/data
    command: "-p 6779"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 6779 -U postgres -d my_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 0s

  server:
    image: server:1.0.0
    container_name: server-c-mup
    build: 
      context: ./muscle-up-backend
      dockerfile: Dockerfile  
    env_file: 
      - .env
    environment:
        DATABASE_URL: ${DATABASE_URL}
    ports:
      - 5006:${PORT}
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./muscle-up-backend:/muscle-up-backend
      - muscle-up-backend-node-modules:/muscle-up-backend/node_modules

volumes:
  muscle-up-backend-node-modules:
    name: "muscle-up-backend-node-modules"
  database-v-mup:
    name: "database-v-mup"